Repository ManageIQ/workflows-examples, pull requests merged in 2023-10, with the labels that each got.

#11 Use Context.Execution for api_url
  provision-vm-service/list-providers.asl
  provision-vm-service/list-templates.asl
  provision-vm-service/provision-vm.asl
Labels: enhancement

#12 Add dynamic verify ssl option
  provision-vm-service/list-providers.asl
  provision-vm-service/list-templates.asl
  provision-vm-service/provision-vm.asl
Labels: enhancement

#13 Fix invalid vcenter user/password variables
  provision-vm-service/power-on-vm/power-on-vm.rb
Labels: bug

#14 Various minor cleanup and consistency
  provision-vm-service/check-task-complete/check-task-complete.rb
  provision-vm-service/clone-template/clone-template.rb
  provision-vm-service/list-providers.asl
  provision-vm-service/list-providers/Dockerfile
  provision-vm-service/list-providers/list-providers.rb
  provision-vm-service/list-templates.asl
  provision-vm-service/list-templates/Dockerfile
  provision-vm-service/list-templates/list-templates.rb
  provision-vm-service/power-on-vm/power-on-vm.rb
  provision-vm-service/provision-vm.asl
Labels: cleanup

#16 Add detailed docs for the provision-vm-service example
  README.md
  provision-vm-service/README.md
  provision-vm-service/provision-vm.png
  provision-vm-service/sample_credentials.json
Labels: documentation

#17 Various doc fixes
  provision-vm-service/README.md
Labels: documentation
